DEFAULT_NUM_WORKERS = 2
DEFAULT_HTTP_PORT = 80
DEFAULT_TIMEOUT = 10
DEFAULT_BACKLOG = 100


PROXY_AGENT_HEADER_VALUE = b'Rzhevsky proxy'

CRLF = b'\r\n'
COLON = b':'
WHITESPACE = b' '
COMMA = b','
DOT = b'.'
SLASH = b'/'
HTTP_1_1 = b'HTTP/1.1'
